### ISSUE TITLE
Mimestream crash on application start

### ISSUE THREAD

**Issue by drr3w** [mimestream/new-bugs#26]
**Crash logs**
[mimestream_crash.zip](https://github.com/mimestream/new-bugs/files/5373763/mimestream_crash.zip)

**To Reproduce**
App is crashing immediately after starting it.
1.  Start application
2. Crash

**Configuration:**
 - OS:  MacOS Catalina
 - Mimestream Version v0.6.25 (99)

**Comment by neiljhaveri** [comment]
This is fixed in v0.6.26+
Please download the latest version from the website and manually replace your copy
or run "rm -rf ~/Library/Containers/com.mimestream.Mimestream" in Terminal

thanks for reporting this!
