### ISSUE TITLE
Clicking Delete Spam button crashes app

### ISSUE THREAD

**Issue by wkeving** [mimestream/new-bugs#29]
**Crash logs**
[Mimestream Crash Logs Archive.zip](https://github.com/mimestream/new-bugs/files/5379619/Mimestream.Crash.Logs.Archive.zip)

**To Reproduce** 
1. Go to "Spam" folder by clicking on it in the left-hand window pane.
2. Click on "Delete Spam" button at top of message list.
3. Crash

**Configuration:**
 - OS: macOS Catalina, v. 10.15.6 (19G2021)
 - Mimestream Version 0.7.0c (101)

**Comment by neiljhaveri** [comment]
I'm already tracking a issue where this occurs if you have a lot of messages, 200+. Is your case less than that a many messages?

**Comment by wkeving** [comment]
Definitely more that that. I think close to 500.

**Comment by neiljhaveri** [comment]
Ok! v0.7.1 fixes this, thanks for reporting it!
