### ISSUE TITLE
Replying and changing subject line does not create a new thread

### ISSUE THREAD

**Issue by fcarrus** [mimestream/new-bugs#35]
**Describe the bug**
In gmail, when replying to a message while also changing the subject line, the new message starts a new thread/conversation. This is visible when using the conversation view mode on.
While doing the same in Mimestream, the reply message created belongs to the original conversation.
It does not seem a visualization issue as the messages created from Mimestream also affect the visualization in gmail.
I suspect it has something to do with keeping the old Message-ID header.

**To Reproduce**
1. Pick any previously sent or received message
2. Reply to it and also change the subject line (this is usually for templating purposes, i.e. to reuse recipients and text from previous messages)
3. Observe the newly sent reply as belonging to the previous conversation, reporting the old subject line in the conversation
4. Repeat on gmail from step 2: observe the newly sent reply starting a new thread, reporting the new subject line in the conversation

**Expected behavior**
A new conversation should be created. 

**Configuration:**
 - OS: macOS Catalina 10.15.7
 - Mimestream Version 0.7.0c (101)

**Comment by avigotsky** [comment]
This bug is about the only one I've found that affects my workflow. Do you think it will be addressed any time soon? Thank you!
