### ISSUE TITLE
Wrong Font Size Upon Change

### ISSUE THREAD

**Issue by Penguinlay** [mimestream/new-bugs#36]
**Describe the bug**
Font size is off by two.

**To Reproduce**
1. If you have text already, select it first.
2. Change font size in editor window.
3. Start writing if you don't have text already.
4. Either way, it will auto select two sizes higher than the one you choose.

**Expected behavior**
Change the font size to the selected one.

**Screenshots**
![CleanShot 2020-10-16 at 03 50 33](https://user-images.githubusercontent.com/13214144/96250149-3b89d600-0f63-11eb-8075-1ad1cdb33792.gif)

**Configuration:**
 - OS: macOS Big Sur 11.0 Beta (20A5395g)
 - Mimestream: Version 0.7.0c (101)

**Comment by neiljhaveri** [comment]
Thanks for reporting this, and sorry it's taken me so long to review this bug! 

Good news, this should be fixed as of v0.7.5!

**Comment by Penguinlay** [comment]
Glad to hear it!
