### ISSUE TITLE
Mimestream quits unexpectedly on start

### ISSUE THREAD

**Issue by dgitman** [mimestream/new-bugs#50]
**Crash logs**
[Mimestream_2020-11-06-155200_Davids-MacBook-Pro.txt](https://github.com/mimestream/new-bugs/files/5503477/Mimestream_2020-11-06-155200_Davids-MacBook-Pro.txt)

**To Reproduce**
Open Mimestream

**Configuration:**
 - OS: macOS Big Sur 11.0 Beta (20A5395g)
 - Mimestream Version: 0.7.4

**Comment by neiljhaveri** [comment]
Thanks for reporting this bug, and sorry about my delay. Can you try opening Terminal and running: `rm -rf ~/Library/Containers/com.mimestream.Mimestream/Data/Library/Saved\ Application\ State/`

Then try launching Mimestream, hopefully it will open. 
How many drafts do you have? Can you go to Drafts and try to open them and see if trying to open any of them causes a crash?
