### ISSUE TITLE
Email info goes beyond email card

### ISSUE THREAD

**Issue by ysmaliak** [mimestream/new-bugs#58]
**Description**
In selected state email info goes beyond email card

**To Reproduce**
1. Go to email
2. Click on any email
3. Swipe in any direction

**Expected behavior**
Email info should be visible only on the card

**Screenshots**
<img width="1176" alt="Screenshot 2020-11-25 at 13 31 50" src="https://user-images.githubusercontent.com/42275599/100216351-3dac6080-2f23-11eb-9648-928f1b6c01cb.png">

**Configuration:**
 - OS: macOS 11.0.1
 - Mimestream Version v0.7.7

**Comment by neiljhaveri** [comment]
This seems to be an AppKit bug affecting any NSTableRowView subclass that overrides drawSeparator(in:). I reported this to Apple as FB8902658.
