### ISSUE TITLE
Impossible to delete email contacts

### ISSUE THREAD

**Issue by Vrokin** [mimestream/new-bugs#62]
**Describe the bug**
One can not delete a contact.
I have once entered a wrong email address, I can not get rid of it.
I have connected directly to gmail to delete de contact with the wrong email address but it remains in mimesteam autocompletion. I have reset the cache but without success.

**To Reproduce**
1. Go to gmail.com and delete a contact
2. Go to mimesteam, and click on compose new message.
3. Enter the first letters of the deleted contact in the 'To:' field.
4. The deleted contact will still be visible into the autocompletion.

**Expected behavior**
Deleted contacts should not appear in email address autocompletion.

**Configuration:**
 - OS: macOS Big Sur
 - Mimestream Version 0.7.7 (109)

**Comment by neiljhaveri** [comment]
Right now autocompletion is based off (1) recent emails, and (2) the macOS Contacts App. [Google Contacts integration](https://portal.productboard.com/mimestream/1-mimestream-roadmap/c/71-better-recipient-autocomplete-from-google-contacts-directory) isn't complete yet.

Maybe you have a message in your account with this bad address, perhaps a Draft in Trash? Can you try doing a search for just the address? Note that search won't currently pull up results in Trash.

**Comment by Vrokin** [comment]
I have delete all the emails containing the wrong email adresses. They do not appear anymore in the "To:" autocompletion.
Thanks !
