### ISSUE TITLE
Cannot change attachment name on save

### ISSUE THREAD

**Issue by AntonTsaberyaby** [mimestream/new-bugs#64]
**Describe the bug**
Hello! Cannot change attachment name on save. When you try to save attachment with a different name, you are not able to do. I tried to save and rename in a save window. I can't rename it (because by some reason I couldn't  change the key source). In my case I tried to change it to Russian and put the russian name for attachment

**To Reproduce**
1. Go to Attachment and will try to save it
2. In the dialog window try to rename the file to name on different language 
4. You will not be able to do this

**Expected behavior**
Ability to save attachment with different names on different languages 

**Configuration:**
 - OS: macOS Big Sur
 - Mimestream Version 0.8.1 (112)

**Comment by neiljhaveri** [comment]
Thank you for reporting this bug! Unfortunately, I tried and was unable to reproduce this. Would you mind possibly attaching a screen recording of the exact steps you are taking to run into this issue?  Thank you!

**Comment by AntonTsaberyaby** [comment]
Can't reproduce this on latest version 0.8.5 (116). @neiljhaveri  Thanks!
