### ISSUE TITLE
New signature not loaded in preferences after adding on Gmail site (even after relaunch)

### ISSUE THREAD

**Issue by rfbarraza** [mimestream/new-bugs#77]
**Description**
I added a new signature on Gmail and exprected the app to reload preferences. But it didn’t. Quit. Relaunched and opened prefs and the sig was still missing.

**Reproducibility**
Always

**To Reproduce**
1. Launch Mimestream
2. Open Preferences
3. Select signature
4. Click the Open Gmail Settings button
5. In Gmail, make a cool new signature. (Be sure to save it with the button at the bottom of your prefs editor)
6. Notice Mimestream doesn’t show the signature. Even if you quit and relaunch

**Expected Behavior**
For the signatue to be displayed if I select another preference and then re-select signatures. Or if I close and re-open preferences. Or if I quit and relaunch Mimestream

**Configuration**
- OS: 10.15.7 (19H114)
- Mimestream: 0.8.4 (115)

**Comment by neiljhaveri** [comment]
Unfortunately Gmail doesn't expose multiple signatures via the API, only the default signature for new messages on a per-alias basis, see
https://issuetracker.google.com/issues/157581366

I'll need to offer a way to create additional client-side signatures, but am tracking that as a feature at
https://portal.productboard.com/mimestream/1-mimestream-roadmap/c/45-better-signature-configurability

**Comment by neiljhaveri** [comment]
(let me know if this bug is about something else, though, and if your sole signature per alias didn't sync)
