### ISSUE TITLE
"Mark as Unread from Here" is enabled for unread messages

### ISSUE THREAD

**Issue by rfbarraza** [mimestream/new-bugs#84]
**Description**
If you mark a message as unread, you still have the ability to mark it as unread via the message’s contextual menu. (Sorry for these little polish bugs)

**Reproducibility**
Always

**To Reproduce**
1. Select a message (marking it as read)
2.Mark the message as unread via “Mark Message Unread from here"
3.View the contextual menu again and you can still mark the message as unread

**Expected Behavior**
The option to make a message unread to be disabledd or unavailable for unread messages

**Screenshots**
<img width="245" alt="Screen Shot 2021-01-02 at 10 02 38 PM" src="https://user-images.githubusercontent.com/24500089/103472130-ecc03100-4d46-11eb-9439-1347659af6a5.png">

**Configuration**
- OS: 10.15.7 (19H114)
- Mimestream: 0.8.4 (115)

**Comment by neiljhaveri** [comment]
Finally, this is fixed and will go out in the next update.
