### ISSUE TITLE
Hitting tab for autocomplete does not work

### ISSUE THREAD

**Issue by schmincke** [mimestream/new-bugs#95]
**Describe the bug**
When entering a name in a "to" field, hitting tab does no longer auto-complete.
Hitting tab here: https://www.dropbox.com/s/tg16v2cudfcxysy/Screenshot%202021-01-15%20at%2013.39.00.JPG?dl=0 should fill in in the mail address, which mime has identified correctly. But it does nothing

**To Reproduce**
Write email, click on "to", enter name to the level where its only one receipient identified and hit tab. Nothing happens.

**Expected behavior**
It should autocomplete.

**Screenshots**
https://www.dropbox.com/s/tg16v2cudfcxysy/Screenshot%202021-01-15%20at%2013.39.00.JPG?dl=0

**Configuration:**
Latest mimestream, latest osx

**Comment by schmincke** [comment]
Version 0.8.6 (117)
Big Sur 11.1

**Comment by neiljhaveri** [comment]
Thank you for reporting this – it should be fixed in 0.10.2!
