### ISSUE TITLE
Support Gmail's Mark as Read shortcut (Shift + i)

### ISSUE THREAD

**Issue by rkrn** [mimestream/new-bugs#96]
**Describe the bug**
The Gmail mark as read shortcut (**Shift + i**) does not currently work on any inbox or search results.

**To Reproduce**
1. Change Keyboard Shortcuts to Gmail
2. Go to any inbox.
3. Multi-select multiple unread conversations by clicking one and **Shift + Down Arrow** to select others.
4. Press **Shift + i**.

Alternatively:
1. Change Keyboard Shortcuts to Gmail
2. Go to any inbox.
3. Select any unread conversation, which will automatically turn it to read (default setting). Change it back to unread by pressing **Shift + u**.
4. Press **Shift + i**.

**Expected behavior**
**Shift + i** should mark a conversations as read.

**Screenshots**
N/A.

**Configuration:**
 - OS: 10.15.6
 - Mimestream Version 0.11.2 (126)

**Comment by neiljhaveri** [comment]
Agree that in Gmail shortcuts mode these alternates should be available

**Comment by neiljhaveri** [comment]
This is now available in current versions of the app.
